stages:
  - build
  - deploy

variables:
  IMAGE_NAME_FRONTEND: "dkr.tw/sgis/locadescriber:frontend"
  VERSION: "latest"

build_frontend:
  stage: build
  script:
    - docker pull node:latest
    - docker build -f frontend/Dockerfile -t $IMAGE_NAME_FRONTEND-$VERSION src/frontend
    - docker push $IMAGE_NAME_FRONTEND-$VERSION
    - docker system prune -f --volumes || echo "Cleanup skipped"
  tags:
    - sgis-zone101

deploy:
  stage: deploy
  script:
    - bash deploy/deploy.sh
  tags:
    - sgis-zone101